site_web/urls.py
from django.urls import path

from django.conf.urls import url
from . import views
app_name = "site_web"

urlpatterns = [
    path("",views.Abertura.as_view() ,name='home'),

    path('',views.Abertura.as_view(),name='video'),




]

youtube_videos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_web.urls')),
]

site_web/models.py
from django.db import models

# Create your models here.

site_web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from pytube import YouTube
from django.views.generic.base import View
import time


# Create your views here.
site = None

class Abertura(View):

    endereco=None
    def get(self, request):
        if request.is_ajax():
            id_video = request.GET.get('message')
            self.baixar_video(id_video,request)


        return render(request, 'site_web/1.html',{})
    def post(self,request):
        global site
        self.endereco = request.POST['endereco']
        site = self.endereco
        img,list = listar_disponibilidades(self.endereco)


        return render(request, 'site_web/1.html', {'endereco': list,
                                                   'capa_img':img})

    def baixar_video(self,pk,request):
        millis = round(time.time() * 1000)
        VIDEO_URL = site + '='
        yt = YouTube(VIDEO_URL)
        #video = yt.streams[pk]

        video = yt.streams[int(pk)]
        if video.resolution!=None:
            caminho='videos/'+str(millis)+"_resolution_"+video.resolution
        else:
            caminho = 'videos/' + str(millis) + "_resolution_" + "audio"
        path_video = caminho +'/'+str(video.default_filename)
        video.download(caminho)



def listar_disponibilidades(endereco):
    lista = []
    VIDEO_URL = endereco + '='

    yt = YouTube(VIDEO_URL)
    imagem = yt.thumbnail_url
    indice =0

    for stream in yt.streams:

        tex = str(stream).split('"')
        extensao = tex[3].split('/')[1]
        if tex[9]=="False":
            tex[9]="audio"
        dados=[("indice",indice),("type",extensao),("resolucao",tex[5]),("codec",tex[9])]
        lista.append(dict(dados))
        indice=indice+1



    return imagem,lista

site_web/templates/site_web/1.html
{% extends "site_web/base.html" %}

{% block title %} baixavideo {% endblock %}

{% block content %}
{% load static %}
<form id="form_busca" class="form_1" data-toggle="validator" method="post">
     {% csrf_token %}
    <div class="row mb-3">
    <label class="col-sm-4 col-form-label"><h2>link do vídeo</h2></label>

    </div>

  <div class="row mb-3">

    <div class="col-sm-10">
      <div class="input-group input-group-lg form-group">
       <input type="url" name="endereco" placeholder="paste link here(https://www.youtube.com/....)" class="form-control input_link_yout" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>


      </div>
     <p class="text-start text-danger texto_alerta" style="visibility:hidden">A url não corresponde a um endereço válido do youtube</p>
    </div>
      <div class="col-sm-2">
        <div class="input-group input-group-lg">
        <button type="submit" class="btn btn-primary btn_pegar_video">processar</button>
            </div>
    </div>
  </div>


</form>





<div>
    <p class="text-center">
        <img src="{{capa_img}}" class="img-thumbnail capa_img" alt=""></p>
<div class="container">
  <!-- Content here -->


    <table class="table table-dark table-striped table_dados">

  <thead class="table-dark">

      <th scope="col">tipo</th>
      <th scope="col">codec</th>
      <th scope="col">qualidade</th>

      <th scope="col">Download</th>

  </thead>

  <tbody>

   {% for disponivel in endereco %}
   <tr>

   <td>{{disponivel.type}}</td>
       <td>{{disponivel.codec}}</td>
       <td>{{disponivel.resolucao}}</td>



       <td><button type="button" class="btn btn-success btn-lg down" data-indi={{disponivel.indice}} data-url="{% url 'site_web:video'  %}" >Donwload</button></td>
       </tr>

  {% endfor %}
  </tbody>
</table>

</div>
</div>



{% endblock %}

site_web/templates/site_web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/customize.css' %}">
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/customize.js' %}"></script>







    <title>{% block title %} {% endblock %}</title>
</head>
<body>



<!-- modal com spinner -->



       <div class="modal fade" id="loadingModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered d-flex justify-content-center" role="document">
        <div class="spinner-border text-primary" style="width: 5rem; height: 5rem;" role="status">
            <span class="sr-only " ></span>
        </div>
    </div>
</div>


<!-- Image and text -->
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

    <main>

        {% block content %}{% endblock %}

    </main>


</body>
</html>

site_web/templates/site_web/testando.html
{% extends "site_web/base.html" %}

{% block test %}
<h1>OLá</h1>

{% endblock %}